@Host = http://localhost:5166

GET {{Host}}/weatherforecast/
Accept: application/json

###

GET {{Host}}/swagger/

###

GET {{Host}}/flowers

###

GET {{Host}}/flowers/pretty

###

GET {{Host}}/flowers/many
